name: mstools

channels:
  - conda-forge
  - pytorch
  - rdkit

dependencies:
  - python>=3.8
  - pip>=20.0.2
  - tqdm>=4.45.0
  - rdkit>=2020.03.1.0
  - openbabel>=3.1.1
  - pip:
    - typed-argument-parser>=1.6.1
    - git+https://github.com/xiangyan93/mstools
